function [alpha, beta, gamma, th1, th2] = ...
    OptimalAlphaBetaGammaTheta(max_matrix_fxy1, min_matrix_fxy1, max_matrix_fxy2, min_matrix_fxy2, max_matrix_gxy, min_matrix_gxy, max_matrix_hxy, min_matrix_hxy)
% OptimalAlphaTheta(max_mtrx_f,min_mtrx_f, max_mtrx_g,min_mtrx_g)
%
% Obtain the optimal value of alpha, \theta_{1} and \theta_{2} in
% preprocessing the Sylvester matrix
% S_{k_{1},k_{2}}(f,g)
%
% Inputs.
%
% max_mtrx_f : (Matrix) containing entries of maximum magnitude of each
% coefficient of f(x,y) in the Sylvester matrix S_{k1,k2}
%
% min_mtrx_f : (Matrix) containing entries of maximum magnitude of each
% coefficient of f(x,y) in the Sylvester matrix S_{k1,k2}
%
% max_matrix_fxy2 : (Matrix)
%
% min_matrix_fxy2 : (Matrix)
%
% max_mtrx_g : (Matrix) containing entries of maximum magnitude of each
% coefficient of g(x,y) in the Sylvester matrix S_{k1,k2}
%
% min_mtrx_g : (Matrix) containing entries of maximum magnitude of each
% coefficient of g(x,y) in the Sylvester matrix S_{k1,k2}
%
% max_matrix_hxy : (Matrix)
%
% min_matrix_hxy : (Matrix)
%
%
% Outputs
%
% alpha : (Float) Optimal value \alpha such that the two partitions of
% S_{k_{1},k_{2}} are balanced.
%
% beta : (Float)
%
% gamma : (Float)
%
% th1 : (Float) Optimal value of \theta_{1}
%
% th2 : (Float) Optimal value of \theta_{2}



% Get the degree of polynomial f(x,y)
[m1, m2] = GetDegree_Bivariate(max_matrix_fxy1);
[n1, n2] = GetDegree_Bivariate(max_matrix_gxy);
[o1, o2] = GetDegree_Bivariate(max_matrix_hxy);
% Assemble the four submatrices of Matrix A

nCoefficients_fxy = (m1 + 1) * (m2 + 1);
nCoefficients_gxy = (n1 + 1) * (n2 + 1);
nCoefficients_hxy = (o1 + 1) * (o2 + 1);

v_i1_f = GetAsVector(diag(0 : 1 : m1) * ones(m1 + 1, m2 + 1));
v_i2_f = GetAsVector(ones(m1 + 1, m2 + 1) * diag(0 : 1 : m2));

v_i1_g = GetAsVector(diag(0 : 1 : n1) * ones(n1 + 1, n2 + 1));
v_i2_g = GetAsVector(ones(n1 + 1, n2 + 1) * diag(0 : 1 : n2));

v_i1_h = GetAsVector(diag(0 : 1 : o1) * ones(o1 + 1, o2 + 1));
v_i2_h = GetAsVector(ones(o1 + 1, o2 + 1) * diag(0 : 1 : o2));


method = 'alpha_beta_gamma';
switch method
    
    case 'alpha_beta_gamma'
        
        % Define vector f
        f = [1 -1 0 0 0 0 0];
        
        A1 = ...
            [
            ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            -1 .* v_i1_f ...
            -1 .* v_i2_f ...
            -ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1)
            ];
        
        A2 = ...
            [
            ones(nCoefficients_gxy, 1) ...
            zeros(nCoefficients_gxy, 1) ...
            -1.* v_i1_g ...
            -1.* v_i2_g ...
            zeros(nCoefficients_gxy,1)...
            -1.* ones(nCoefficients_gxy, 1) ...
            zeros(nCoefficients_gxy,1)
            ];
        
        A3 = ...
            [
            ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            -1.* v_i1_f ...
            -1.* v_i2_f ...
            zeros(nCoefficients_fxy, 1)...
            zeros(nCoefficients_fxy, 1) ...
            -1.* ones(nCoefficients_fxy, 1)
            ];
        
        A4 = ...
            [
            ones(nCoefficients_hxy, 1) ...
            zeros(nCoefficients_hxy, 1) ...
            -1.* v_i1_h ...
            -1.* v_i2_h ...
            zeros(nCoefficients_hxy,1)...
            -1.* ones(nCoefficients_hxy, 1) ...
            zeros(nCoefficients_hxy, 1)
            ];
        
        a1 = ...
            [
            zeros(nCoefficients_fxy, 1) ...
            -ones(nCoefficients_fxy, 1) ...
            v_i1_f ...
            v_i2_f ...
            ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            ];
        
        a2 = ...
            [
            zeros(nCoefficients_gxy,1) ...
            -ones(nCoefficients_gxy,1) ...
            v_i1_g ...
            v_i2_g ...
            zeros(nCoefficients_gxy,1) ...
            ones(nCoefficients_gxy,1) ...
            zeros(nCoefficients_gxy,1)
            ];
        
        a3 = ...
            [
            zeros(nCoefficients_fxy, 1) ...
            -ones(nCoefficients_fxy, 1) ...
            1.* v_i1_f ...
            1.* v_i2_f ...
            zeros(nCoefficients_fxy, 1)...
            zeros(nCoefficients_fxy, 1) ...
            ones(nCoefficients_fxy, 1)
            ];
        
        a4 = ...
            [
            zeros(nCoefficients_hxy, 1) ...
            -ones(nCoefficients_hxy, 1) ...
            1.* v_i1_h ...
            1.* v_i2_h ...
            zeros(nCoefficients_hxy,1)...
            1.* ones(nCoefficients_hxy, 1) ...
            zeros(nCoefficients_hxy, 1)
            ];
        
    case 'alpha_beta'
        % Define vector f
        f = [1 -1 0 0 0 0];
    case 'alpha_gamma'
        
        % Define vector f
        f = [1 -1 0 0 0 0];
        
        A1 = ...
            [
            ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            -1 .* v_i1_f ...
            -1 .* v_i2_f ...
            -ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1)
            ];
        
        A2 = ...
            [
            ones(nCoefficients_gxy, 1) ...
            zeros(nCoefficients_gxy, 1) ...
            -1.* v_i1_g ...
            -1.* v_i2_g ...
            zeros(nCoefficients_gxy,1)...
            zeros(nCoefficients_gxy,1)
            ];
        
        A3 = ...
            [
            ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            -1.* v_i1_f ...
            -1.* v_i2_f ...
            zeros(nCoefficients_fxy, 1)...
            -1.* ones(nCoefficients_fxy, 1)
            ];
        
        A4 = ...
            [
            ones(nCoefficients_hxy, 1) ...
            zeros(nCoefficients_hxy, 1) ...
            -1.* v_i1_h ...
            -1.* v_i2_h ...
            zeros(nCoefficients_hxy,1)...
            zeros(nCoefficients_hxy, 1)
            ];
        
        a1 = ...
            [
            zeros(nCoefficients_fxy, 1) ...
            -ones(nCoefficients_fxy, 1) ...
            v_i1_f ...
            v_i2_f ...
            ones(nCoefficients_fxy, 1) ...
            zeros(nCoefficients_fxy, 1) ...
            ];
        
        a2 = ...
            [
            zeros(nCoefficients_gxy,1) ...
            -ones(nCoefficients_gxy,1) ...
            v_i1_g ...
            v_i2_g ...
            zeros(nCoefficients_gxy,1) ...
            zeros(nCoefficients_gxy,1)
            ];
        
        a3 = ...
            [
            zeros(nCoefficients_fxy, 1) ...
            -ones(nCoefficients_fxy, 1) ...
            1.* v_i1_f ...
            1.* v_i2_f ...
            zeros(nCoefficients_fxy, 1)...
            ones(nCoefficients_fxy, 1)
            ];
        
        a4 = ...
            [
            zeros(nCoefficients_hxy, 1) ...
            -ones(nCoefficients_hxy, 1) ...
            1.* v_i1_h ...
            1.* v_i2_h ...
            zeros(nCoefficients_hxy,1)...
            zeros(nCoefficients_hxy, 1)
            ];
    case 'beta_gamma'
        % Define vector f
        f = [1 -1 0 0 0 0];
end

% Now build the vector b
B1 = GetAsVector(abs(max_matrix_fxy1));
B2 = GetAsVector(abs(max_matrix_gxy));
B3 = GetAsVector(abs(max_matrix_fxy2));
B4 = GetAsVector(abs(max_matrix_hxy));

b1 = GetAsVector(abs(min_matrix_fxy1));
b2 = GetAsVector(abs(min_matrix_gxy));
b3 = GetAsVector(abs(min_matrix_fxy2));
b4 = GetAsVector(abs(min_matrix_hxy));

% % Find any zeros in the lambda vector
indeces = find(B1 == 0);
A1(indeces,:) = [];
B1(indeces,:) = [];

% Find any zeros in the mu vector
indeces = find(B2 == 0);
A2(indeces,:) = [];
B2(indeces,:) = [];

% % Find any zeros in the lambda vector
indeces = find(B3 == 0);
A3(indeces,:) = [];
B3(indeces,:) = [];

% % Find any zeros in the lambda vector
indeces = find(B4 == 0);
A4(indeces,:) = [];
B4(indeces,:) = [];

% Find any zeros in the rho vector
indeces = find(b1 == 0);
a1(indeces,:) = [];
b1(indeces,:) = [];

% % Find any zeros in the lambda vector
indeces = find(b2 == 0);
a2(indeces,:) = [];
b2(indeces,:) = [];

% Find any zeros in the tau vector
indeces = find(b3 == 0);
a3(indeces,:) = [];
b3(indeces,:) = [];


% % Find any zeros in the lambda vector
indeces = find(b4 == 0);
a4(indeces,:) = [];
b4(indeces,:) = [];

b = [log10(B1);
    log10(B2);
    log10(B3);
    log10(B4);
    -log10(b1);
    -log10(b2);
    -log10(b3);
    -log10(b4)];

A = [A1; A2; A3; A4; a1; a2; a3; a4];

warning('off')
x = linprog(f,-A,-b);
warning('on')

try
    switch method
        case 'alpha_beta_gamma'
            th1 = 10^x(3);
            th2 = 10^x(4);
            alpha  = 10^x(5);
            beta = 10^x(6);
            gamma = 10^x(7);
            
            
        case 'alpha_gamma'
            th1 = 10^x(3);
            th2 = 10^x(4);
            alpha  = 10^x(5);
            beta = 1;
            gamma = 10^x(6);
            
        otherwise
            error('Error')
    end
    
catch
    alpha = 1;
    beta = 1;
    gamma = 1;
    th1 = 1;
    th2 = 1;
end

end